#!/bin/bash

set -ex

if [ $# -ne 2 ]
  then
    echo "usage: $0 <old version> <new version>"
    exit 1
fi

OLDVERSION=$1
NEWVERSION=$2

# bumps the runtime version in the Cargo.toml and runtime lib.rs files
sd "spec_version: $OLDVERSION" "spec_version: $NEWVERSION" runtime/**/src/lib.rs
sd "version = \"$OLDVERSION" "version = \"$NEWVERSION" runtime/**/Cargo.toml